name = "erdos_lean_env"
defaultTargets = ["Env"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "df3f12d7bd06feb3f71ae37abae0ca7cb798d9b1"

[[lean_lib]]
name = "Env"
